#include <lcom/lcf.h>

#include <lcom/lab6.h>

#include <stdint.h>
#include <stdio.h>

#include "rtc.h"


int main(int argc, char *argv[]) {
    // sets the language of LCF messages (can be either EN-US or PT-PT)
    lcf_set_language("EN-US");

    // enables to log function invocations that are being "wrapped" by LCF
    // [comment this out if you don't want/need it]
    lcf_trace_calls("/home/lcom/labs/lab6/trace.txt");

    // enables to save the output of printf function calls on a file
    // [comment this out if you don't want/need it]
    lcf_log_output("/home/lcom/labs/lab6/output.txt");

    // handles control over to LCF
    // [LCF handles command line arguments and invokes the right function]
    if (lcf_start(argc, argv))
        return 1;

    // LCF clean up tasks
    // [must be the last statement before return]
    lcf_cleanup();

    return 0;
}

int rtc_test_conf(){
    //Read the control/status registers of the RTC, and display the information in a human friendly way
    uint8_t regA, regB, regC;
    if(rtc_read_register(RTC_REG_A, &regA)){
        printf("Error reading register A\n");
        return 1;
    }

    if(rtc_read_register(RTC_REG_B, &regB)){
        printf("Error reading register B\n");
        return 1;
    }

    if(rtc_read_register(RTC_REG_C, &regC)){
        printf("Error reading register C\n");
        return 1;
    }

    printf("Register A: 0x%x\n", regA);
    printf("Register B: 0x%x\n", regB);
    printf("Register C: 0x%x\n", regC);

    return 0;
}

int rtc_test_date(){
    //Read the date/time registers of the RTC

    return 0;
}
int rtc_test_int(){
    //Handle one of the interrupt events generated by the RTC
    return 0;
}
